// <auto-generated />
using LexiconGruppProject1_grupp7.Infrastructure.Presistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LexiconGruppProject1_grupp7.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250609085730_Init -with stories")]
    partial class Initwithstories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LexiconGruppProject1_grupp7.Domain.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Tilda the turtle was slow—but she never gave up. One day, she challenged Ricky the Rabbit to a race.\r\n“Ha! You’ll never win!” laughed Ricky.\r\nThe race began. Ricky zoomed ahead but stopped for a nap under a shady tree. Tilda kept going. Step by step. Slow but steady.\r\nWhen Ricky woke up—Tilda was already at the finish line!\r\n“Never underestimate a turtle,” she said with a smile.",
                            Title = "Tilda the Turtle's Big Race"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Olly the octopus loved colors but didn’t know how to paint. He tried to copy the seahorses, but he kept getting paint on his arms!\r\n“Maybe painting isn’t for me,” he sighed.\r\nThen he had an idea: why not paint with all eight arms at once?\r\nHe swirled, splashed, and danced—soon the ocean floor was filled with beautiful, colorful shapes!\r\nNow everyone comes to Olly’s Art Show every Sunday.",
                            Title = "Olly the Octopus Learns to Paint"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Benny the bird found a red balloon stuck in a tree.\r\n“It’s too high!” he chirped. “But I must help!”\r\nHe called his friends—Milly the mouse, Freddy the frog, and Lily the ladybug. Together they made a tower!\r\nMilly stood on Freddy, Freddy on Lily, and Benny flew up top—POP! The balloon floated free and everyone cheered.\r\nThey didn’t keep the balloon—but they kept the memory.",
                            Title = "Benny and the Stuck Balloon"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
